services:
  react_app:
    build: ./react_app
    container_name: react_app
    env_file:
      - .env
    ports:
      - 8000:8000

  mqtt_app:
    build: ./mqtt_app
    container_name: mqtt_app
    env_file:
      - .env
    depends_on:
      - mosquitto
    networks:
      - all_networks

  rest_app:
    build: ./rest_app
    container_name: rest_app
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - all_networks

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - all_networks

networks:
  all_networks:
    driver: bridge